services:
  - type: web
    name: cv-offer-compare-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 300 --timeout-graceful-shutdown 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: SSE_TIMEOUT
        value: "300"
      - key: MAX_CONCURRENT_REQUESTS
        value: "10" 